# Generated by Django 3.0.5 on 2022-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20220414_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='size',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('XL', 'XL')], max_length=200, null=True),
        ),
    ]
