# Generated by Django 3.0.5 on 2022-04-25 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_drink_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakeitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('discount', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaypal', models.PositiveIntegerField()),
                ('datePay', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_date',
            new_name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='cake',
            name='expiry',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='expiry',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('Giải khát', 'Giải khát'), ('Nước ngọt', 'Nước ngọt'), ('Trà sữa', 'Trà sữa')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMoney', models.FloatField()),
                ('paypal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Paypal')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Drinkitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('discount', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=40)),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('cakeitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Cakeitem')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
                ('drinkitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Drinkitem')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True, null=True)),
                ('totalMoney', models.FloatField()),
                ('cakeitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Cakeitem')),
                ('drinkitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Drinkitem')),
            ],
        ),
        migrations.AddField(
            model_name='cakeitem',
            name='cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Cake'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Cart'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Payment'),
        ),
    ]
