# Generated by Django 4.0.2 on 2022-05-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20220425_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='description',
        ),
    ]
