# Generated by Django 3.0.5 on 2022-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20220425_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalMoney',
            field=models.FloatField(null=True),
        ),
    ]
