# Generated by Django 4.0.2 on 2022-03-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product2_alter_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
